name: Publish
on:
  push:
    branches:
      - main
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: |
          latestVersion=$(npm view @jim-brighter/lambda-local-runner version)
          npm version $latestVersion --allow-same-version --no-commit-hooks --no-git-tag-version
          commitMessage="${{ github.event.head_commit.message }}"
          if [[ "$commitMessage" == *"(version:major)"* ]]; then
            npm version major --no-commit-hooks --no-git-tag-version
          elif [[ "$commitMessage" == *"(version:minor)"* ]]; then
            npm version minor --no-commit-hooks --no-git-tag-version
          else
            npm version patch --no-commit-hooks --no-git-tag-version
          fi
          npm i
          npm run pub
