name: PR Build
on:
  pull_request:
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: |
          npm i
      - name: Check Semver
        run: |
          currentVersion=$(npm pkg get version | tr -d '"')
          echo $currentVersion
          latestVersion=$(npm view @jim-brighter/lambda-local-runner version)
          echo $latestVersion
          if [[ $currVersion == $latestVersion ]]; then
            echo "=== VERSION BUMP REQUIRED ==="
            exit 1
          fi
